/* Code generated by binutils_generator.py --inst-dir ../../../spec/custom/isa/example/inst --extensions CustomTest; DO NOT EDIT. */
/* This file should be placed at: binutils-gdb/opcodes/riscv-opc.c */

#include "opcode/riscv.h"

const struct riscv_opcode riscv_opcodes[] = {
  {"test.complex.imm", 0, INSN_CLASS_CUSTOMTEST, "s,t,p", MATCH_TEST_COMPLEX_IMM, MASK_TEST_COMPLEX_IMM, match_opcode, 0},
  {"test.csr.ops", 0, INSN_CLASS_CUSTOMTEST, "d,,s", MATCH_TEST_CSR_OPS, MASK_TEST_CSR_OPS, match_opcode, 0},
  {"test.fence.ops", 0, INSN_CLASS_CUSTOMTEST, "P,Y", MATCH_TEST_FENCE_OPS, MASK_TEST_FENCE_OPS, match_opcode, 0},
  {"test.float.ops", 0, INSN_CLASS_CUSTOMTEST, "D,S,T,", MATCH_TEST_FLOAT_OPS, MASK_TEST_FLOAT_OPS, match_opcode, 0},
  {"test.load.store", 0, INSN_CLASS_CUSTOMTEST, "o,s", MATCH_TEST_LOAD_STORE, MASK_TEST_LOAD_STORE, match_opcode, 0},
  {"test.reg.imm", 0, INSN_CLASS_CUSTOMTEST, "d,s,j", MATCH_TEST_REG_IMM, MASK_TEST_REG_IMM, match_opcode, 0},
  {"test.reg.reg", 0, INSN_CLASS_CUSTOMTEST, "d,s,t", MATCH_TEST_REG_REG, MASK_TEST_REG_REG, match_opcode, 0},
  {"test.shift.ops", 0, INSN_CLASS_CUSTOMTEST, "d,s,>", MATCH_TEST_SHIFT_OPS, MASK_TEST_SHIFT_OPS, match_opcode, 0},
  {"test.unusual.bits", 0, INSN_CLASS_CUSTOMTEST, "no_match_weird_dst_15_11,no_match_weird_src_23_19,no_match_weird_imm_30_25", MATCH_TEST_UNUSUAL_BITS, MASK_TEST_UNUSUAL_BITS, match_opcode, 0},
  {"test.upper.imm", 0, INSN_CLASS_CUSTOMTEST, "d,u", MATCH_TEST_UPPER_IMM, MASK_TEST_UPPER_IMM, match_opcode, 0}
};
