/* Code generated by binutils_generator.py --inst-dir ../../../spec/custom/isa/example/inst --extensions CustomTest; DO NOT EDIT. */
/* This file should be placed at: binutils-gdb/include/opcode/riscv.h (append to existing file) */

#ifndef RISCV_OPC_H
#define RISCV_OPC_H

/* RISC-V opcode constants for 10 instructions */

/* Custom instruction class definitions */
/* Add these to your binutils enum riscv_insn_class in include/opcode/riscv.h */
/* INSN_CLASS_CUSTOMTEST, */

/* MATCH constants */
#define MATCH_TEST_COMPLEX_IMM 0x63
#define MATCH_TEST_CSR_OPS 0x1073
#define MATCH_TEST_FENCE_OPS 0xf
#define MATCH_TEST_FLOAT_OPS 0x53
#define MATCH_TEST_LOAD_STORE 0x1023
#define MATCH_TEST_REG_IMM 0x40b3
#define MATCH_TEST_REG_REG 0xfe000073
#define MATCH_TEST_SHIFT_OPS 0x1013
#define MATCH_TEST_UNUSUAL_BITS 0x53
#define MATCH_TEST_UPPER_IMM 0x37

/* MASK constants */
#define MASK_TEST_COMPLEX_IMM 0x707f
#define MASK_TEST_CSR_OPS 0x707f
#define MASK_TEST_FENCE_OPS 0x7807fff
#define MASK_TEST_FLOAT_OPS 0xfe00707f
#define MASK_TEST_LOAD_STORE 0xfe00707f
#define MASK_TEST_REG_IMM 0x7ffff
#define MASK_TEST_REG_REG 0xfe00707f
#define MASK_TEST_SHIFT_OPS 0xfe00707f
#define MASK_TEST_UNUSUAL_BITS 0x707f
#define MASK_TEST_UPPER_IMM 0x7f

#endif /* RISCV_OPC_H */
