/* Code generated by binutils_generator.py --inst-dir ../../../spec/custom/isa/example/inst --extensions CustomTest; DO NOT EDIT. */
/* This file contains code snippets that should be added to: binutils-gdb/bfd/elfxx-riscv.c */

/* Add these cases to riscv_multi_subset_supports() in bfd/elfxx-riscv.c */

/* Cases for riscv_multi_subset_supports() switch statement */
    case INSN_CLASS_CUSTOMTEST:
      return riscv_subset_supports (rps, "customtest");

/* Cases for riscv_multi_subset_supports_ext() switch statement */
    case INSN_CLASS_CUSTOMTEST:
      return "customtest";


/* Instructions for integration:
 * 
 * 1. Add the instruction classes to include/opcode/riscv.h:
 *    (Already listed in the generated .h file)
 *
 * 2. Add these cases to the switch statement in bfd/elfxx-riscv.c:
 *    - Find function riscv_multi_subset_supports()
 *    - Add the cases above to the switch statement
 *    - Find function riscv_multi_subset_supports_ext()  
 *    - Add the ext cases above to the switch statement
 *
 * 3. Extension names are converted to lowercase in subset support functions
 */
